### ISSUE TITLE
How to add function as a props in renderGridItem

### ISSUE THREAD

**Issue by beltrancaliz** [toystars/react-native-layout-grid#1]
- I am trying to pass a functions as props for onPress, however I keep getting errors stating that props is undefined.
- Is there a way to do this without having to edit the GridLayout component?
- Here is my code:

```
renderGridItem(item){
   return (
   <TouchableOpacity
     style={[styles.item, {backgroundColor: item.color}]}
     onPress={this.props.onClose.bind(this)}
   >

     <View style={styles.flex} />
     <View style={{justifyContent: 'center', alignItems: 'center', marginBottom: 5}} >
     <Icon name={item.icon} size={60} style={{color: 'white'}} />
     </View>
     <Text style={styles.name}>
       {item.name}
     </Text>
   </TouchableOpacity>
  );
 };
```

Thanks in advance

**Comment by ferdinandarmalim** [comment]
Have you found the solution @beltrancaliz? I am facing the same problem here.

**Comment by ferdinandarmalim** [comment]
Nevermind, I have found the solution. You just need to add `this.renderGridItem = this.renderGridItem.bind(this)` on your constructor.

It should fix your problem.

**Comment by toystars** [comment]
@beltrancaliz @ferdinandarmalim or you could just have the `renderGridItem` as an arrow function like below, which uses class `this` by default. Using `bind` works too.

```
renderGridItem = item => (
   <TouchableOpacity
     style={[styles.item, {backgroundColor: item.color}]}
     onPress={this.props.onClose.bind(this)}
   >
     <View style={styles.flex} />
     <View style={{justifyContent: 'center', alignItems: 'center', marginBottom: 5}} >
     <Icon name={item.icon} size={60} style={{color: 'white'}} />
     </View>
     <Text style={styles.name}>
       {item.name}
     </Text>
   </TouchableOpacity>
  );
```

**Comment by beltrancaliz** [comment]
I ended up switching to `react-native-grid-component` but thank you for the proposed solutions!
